Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'contract/**/*'
    - '.git-hooks/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Enabled: false
